=== BernatskyPavel/BSTU_Labs/CDML/Lab-12/books.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="shelf">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="author" type="xs:string" minOccurs="1" />
                            <xs:element name="title" type="xs:string" minOccurs="1" />
                            <xs:element name="year" type="xs:positiveInteger" minOccurs="1" />
                            <xs:element name="pages" type="xs:positiveInteger" minOccurs="1" />
                            <xs:element name="publisher" type="xs:string" minOccurs="1" />
                            <xs:element name="cover" type="xs:string" minOccurs="1" />
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== BernatskyPavel/BSTU_Labs/CDML/Lab-12/books.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="books.xslt" type="text/xsl"?>
<shelf xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="books.xsd">
    <book>
        <author>Джейсон Уилкс</author>
        <title>Математика в огне. Нескучный учебник</title>
        <year>2020</year>
        <pages>512</pages>
        <publisher>Манн, Иванов и Фербер</publisher>
        <cover>./images/MathOnFire.webp</cover>
    </book>
    <book>
        <author>Макконнелл Стив</author>
        <title>Совершенный код</title>
        <year>2022</year>
        <pages>896</pages>
        <publisher>БХВ-Петербург</publisher>
        <cover>./images/IdealCode.webp</cover>
    </book>
    <book>
        <author>Клабник С., Николс К.</author>
        <title>Программирование на Rust</title>
        <year>2021</year>
        <pages>592</pages>
        <publisher>Питер</publisher>
        <cover>./images/Rust.webp</cover>
    </book>
</shelf>
