=== BernatskyPavel/BSTU_Labs/CDML/Lab-12/marks.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="certification">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:all>
                            <xs:element name="firstname" type="xs:string" minOccurs="1" />
                            <xs:element name="lastname" type="xs:string" minOccurs="1" />
                            <xs:element name="fathername" type="xs:string" minOccurs="0" />
                            <xs:element name="group" type="xs:string" minOccurs="1" />
                            <xs:element name="faculty" type="xs:string" minOccurs="1" />
                            <xs:element name="marks" minOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="mark" maxOccurs="unbounded" type="MarkType" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:all>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="MarkType">
        <xs:all>
            <xs:element name="subject" type="xs:string" minOccurs="1" />
            <xs:element name="value" minOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:positiveInteger">
                        <xs:minInclusive value="1" />
                        <xs:maxInclusive value="10" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:all>
    </xs:complexType>
</xs:schema>

=== BernatskyPavel/BSTU_Labs/CDML/Lab-12/marks.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="marks.xslt" type="text/xsl"?>
<certification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="marks.xsd">
    <student>
        <firstname>Иван</firstname>
        <lastname>Иванов</lastname>
        <fathername>Иванович</fathername>
        <faculty>ИТ</faculty>
        <group>5/2</group>
        <marks>
            <mark>
                <subject>ОИАД</subject>
                <value>6</value>
            </mark>
            <mark>
                <subject>Химия</subject>
                <value>8</value>
            </mark>
            <mark>
                <subject>ПВИ</subject>
                <value>10</value>
            </mark>
        </marks>
    </student>
    <student>
        <firstname>Петр</firstname>
        <lastname>Петров</lastname>
        <faculty>ИТ</faculty>
        <group>1/1</group>
        <marks>
            <mark>
                <subject>Химия</subject>
                <value>2</value>
            </mark>
            <mark>
                <subject>ОИАД</subject>
                <value>4</value>
            </mark>
            <mark>
                <subject>ПВИ</subject>
                <value>6</value>
            </mark>
        </marks>
    </student>
    <student>
        <firstname>Сергей</firstname>
        <lastname>Сергеев</lastname>
        <fathername>Сергеевич</fathername>
        <faculty>ЗО</faculty>
        <group>7/1</group>
        <marks>
            <mark>
                <subject>ПВИ</subject>
                <value>4</value>
            </mark>
            <mark>
                <subject>ОИАД</subject>
                <value>8</value>
            </mark>
            <mark>
                <subject>Химия</subject>
                <value>8</value>
            </mark>
        </marks>
    </student>
</certification>
