<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE shelf [
    <!ELEMENT shelf (book*)>
    <!ELEMENT book (author, title, year, pages, publisher, cover)>
    <!ELEMENT author (#PCDATA)>
    <!ELEMENT title (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT pages (#PCDATA)>
    <!ELEMENT publisher (#PCDATA)>
    <!ELEMENT cover (#PCDATA)>
]>
<shelf>
    <book>
        <author>Джейсон Уилкс</author>
        <title>Математика в огне. Нескучный учебник</title>
        <year>2020</year>
        <pages>512</pages>
        <publisher>Манн, Иванов и Фербер</publisher>
        <cover>./images/MathOnFire.webp</cover>
    </book>
    <book>
        <author>Макконнелл Стив</author>
        <title>Совершенный код</title>
        <year>2022</year>
        <pages>896</pages>
        <publisher>БХВ-Петербург</publisher>
        <cover>./images/IdealCode.webp</cover>
    </book>
    <book>
        <author>Клабник С., Николс К.</author>
        <title>Программирование на Rust</title>
        <year>2021</year>
        <pages>592</pages>
        <publisher>Питер</publisher>
        <cover>./images/Rust.webp</cover>
    </book>
</shelf>